import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import PokemonCard from "@/components/PokemonCard";
import SectionContainer from "@/components/SectionContainer";
import { useEffect, useState } from "react";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
// import required modules
import { Navigation } from "swiper";

export default function Home() {
  // States
  const [data, setData] = useState([]);
  // Styles
  const bgImage = {
    backgroundImage: "url('/Background.png')",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
  };

  const scrollingBgImg = {
    backgroundImage: "url('/Left.png')",
  };

  // Fetch Data
  const fetchData = () => {
    const gqlQuery = `query pokemons($limit: Int, $offset: Int) {
      pokemons(limit: $limit, offset: $offset) {
        count
        next
        previous
        status
        message
        results {
          id
          url
          name
          image
          artwork
        }
      }
    }`;

    const gqlVariables = {
      limit: 12,
      offset: 1,
    };

    fetch("https://graphql-pokeapi.graphcdn.app/", {
      credentials: "omit",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        query: gqlQuery,
        variables: gqlVariables,
      }),
      method: "POST",
    })
      .then((res) => res.json())
      .then((res) => setData(res.data));
  };

  // Componenent will mount
  useEffect(() => fetchData(), []);

  console.log(data);

  return (
    <>
      <Head>
        <title>PokeDex - Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://icons-for-free.com/iconfiles/png/512/go+pikachu+play+pokemon+icon-1320186973527720987.png"
        />
      </Head>
      <main>
        {/* Pokemon Card Container */}
        <div style={bgImage}>
          <SectionContainer>
            <div className="py-5"></div>
            <Image
              className="mx-auto"
              src="/Logo.png"
              alt="Pokemon Logo"
              width={200}
              height={100}
            />
            {/* Card Container */}
            <div className=" py-16">
              {/* Looping through each pokemons */}
              {/* Larger Screen */}
              <div className="hidden md:flex overflow-hidden justify-center md:flex-wrap flex-nowrap gap-2 md:gap-10 justify-self-center  ">
                {data?.pokemons?.results.map((pokemon) => (
                  <PokemonCard key={pokemon.id} pokemon={pokemon} />
                ))}
              </div>
              {/* Small Screen */}
              <div className="block md:hidden">
                <Swiper
                  slidesPerView={2}
                  spaceBetween={30}
                  centeredSlides={true}
                  navigation={true}
                  modules={[Navigation]}
                  className="mySwiper"
                >
                  {data?.pokemons?.results.map((pokemon) => (
                    <SwiperSlide>
                      <PokemonCard key={pokemon.id} pokemon={pokemon} />
                    </SwiperSlide>
                  ))}
                </Swiper>
              </div>
            </div>
          </SectionContainer>
        </div>

        {/* Poke News Container */}
        <div className=" grid md:grid-cols-[80px_1fr_80px]">
          {/* Left scrolling Image */}
          <div
            style={scrollingBgImg}
            className="scrollingImg hidden md:block"
          ></div>
          {/* Main Content */}
          <SectionContainer>
            <div className="relative">
              <img
                src="/Brush.png"
                className="absolute w-1/2 md:max-w-fit top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 -z-10"
                alt=""
              />
              <h2 className="text-3xl lg:text-5xl font-extrabold py-10 md:py-20 text-[#0081c9] text-center">
                Ash & Pikachu Arrive in <br /> Pokemon Universe
              </h2>
            </div>
            {/* News for Large screen */}
            <div className="hidden  lg:grid grid-cols-7 gap-4 text-sm font-bold text-slate-800 break-all pb-20">
              {/* Left Content */}
              <div className="col-span-4  flex flex-col gap-4">
                <div className="grid grid-cols-4 gap-4">
                  {/* Text */}
                  <div className="col-span-3 flex flex-col ">
                    <p>
                      Lorem Ipsum is simply dummy text of the printing and
                      typesetting industry. Lorem Ipsum has been the industry's
                      standard dummy text ever since the 1500s, when an unknown
                      printer took a galley of type and scrambled it to make a
                      type specimen book.C. This book is a treatise on the
                      theory of e
                    </p>
                    {/* Left Middle Content */}
                    <div className="flex py-4 gap-4">
                      <p>
                        Lorem Ipsum is simply dummy text of the printing and
                        typesetting industry. Lorem Ipsum has been the
                        industry's standard dummy text ever since the 1500s,
                        when an unknown printer took a galley of type and
                        scrambled it to make a type specimen book. It has
                        survived not only five.The first line of Lorem Ipsum,
                        "Lorem ipsum dolor sit amet..", comes from a linetext
                        ever since the 1500s, when an unknow
                      </p>
                      <img src="/Image04.png" width="200" height="200" alt="" />
                    </div>
                    <p>
                      Contrary to popular belief, Lorem Ipsum is not simply
                      random text. It has roots in a piece of classical Latin
                      literature from 45 BC, making it over 2000 years old.
                      Richard McClintock, a Latin professor at Hampden-Sydney
                      College in Virginia, looked up one of the more obscure
                      Latin words,
                    </p>
                  </div>
                  {/* Images */}
                  <div className="flex flex-col gap-4 ">
                    <img src="/Image03.png" width="200" height="200" alt="" />
                    <img src="/Image02.png" width="200" height="200" alt="" />
                  </div>
                </div>
                <p>
                  There are many variations of passages of Lorem Ipsum
                  available, but the majority have suffered alteration in some
                  form, by injected humour, or randomised words which don't look
                  even slightly believable. If you are going to use a passage of
                  Lorem Ipsum, you need to be sure there isn't anything
                  embarrassing hidden in the middle of text. All the Lorem Ipsum
                  generators on the Internet tend to repeat predefined chunks as
                  necessary, making this the first true generator on the
                  Internet. It uses a dictionary of over 200 Latin words,
                  combined with a handful of model sentence structures, to
                  generate Lorem Ipsum which looks reasonable. The generated
                  Lorem Ipsum is therefore always free from repetition, injected
                  humour, or non-characteristic words etc.
                </p>
              </div>
              {/* Right Content */}
              <div className="col-span-3 flex flex-col gap-4">
                <p>
                  There are many variations of passages of Lorem Ipsum
                  available, but the majority have suffered alteration in some
                  form, by injected humour, or randomised words which don't look
                  even slightly believable. If y
                </p>
                {/* Image with text */}
                <div className="flex flex-col gap-2">
                  <div className="flex  gap-4">
                    <img src="/Image05.png" width="200" height="200" alt="" />
                    <p>
                      Lorem Ipsum is simply dummy text of the printing and
                      typesetting industry. Lorem Ipsum has been the industry's
                      standard dummy text ever since the 1500s, when an unknown
                      printer took a galley of type and scrambled it to make a
                      type specimen book. It has survived not only five.The
                      first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..",
                      comes from a linetext ever since the 1500s, when an unknow
                    </p>
                  </div>
                  <div className="flex gap-4">
                    <img src="/Image01.png" width="200" height="200" alt="" />
                    <p>
                      Lorem Ipsum is simply dummy text of the printing and
                      typesetting industry. Lorem Ipsum has been the industry's
                      standard dummy text ever since the 1500s, when an unknown
                      printer took a galley of type and scrambled it to make a
                      type specimen book. It has survived not only five.The
                      first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..",
                      comes from a linetext ever since the 1500s, when an unknow
                    </p>
                  </div>
                </div>
                <p>
                  Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                  accusantium doloremque laudantium, totam rem aperiam, eaque
                  ipsa quae ab illo inventore veritatis et quasi architecto
                  beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem
                  quia voluptas sit aspernatur aut odit aut fugit, sed quia
                  consequuntur magni dolores eos qui ratione voluptatem sequi
                  nesciunt. Neque porro quisquam est, qui dolorem ipsum quia
                  dolor sit amet, consectetur, adipisci velit, sed quia non
                  numquam eius modi tempora incidunt ut labore et dolore magnam
                  aliquam quaerat voluptatem. Ut enim ad minima veniam
                </p>
              </div>
            </div>

            {/* News for mobile screen */}
            <div className="block md:hidden px-4 font-bold text-slate-700">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                nulla pariatur. Excepteur sint occaecat cupidatat non proident,
                sunt in culpa qui officia deserunt mollit anim id est laborum
              </p>
              {/* Images */}
              <div className="grid grid-cols-3 gap-3">
                <img src="/Image04.png" className="mt-10" alt="" />
                <div className="flex flex-col gap-3">
                  <img src="/Image03.png" alt="" />
                  <img src="Image02.png" alt="" />
                </div>
                <div className="mt-10 grid gap-3">
                  <img src="/Image05.png" alt="" />
                  <img src="/Image01.png" alt="" />
                </div>
              </div>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                nulla pariatur. Excepteur sint occaecat cupidatat non proident,
                sunt in culpa qui officia deserunt mollit anim id est laborum
              </p>
            </div>
          </SectionContainer>
          {/* Right Scrolling Image */}
          <div
            style={scrollingBgImg}
            className="scrollingImg hidden md:block"
          ></div>
        </div>
      </main>
    </>
  );
}
