import Head from "next/head";
import PokemonCard from "@/components/PokemonCard";
import SectionContainer from "@/components/SectionContainer";
import { useContext, useEffect, useState } from "react";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
// import required modules
import { Navigation } from "swiper";
import Link from "next/link";
import PokemonLogo from "@/components/PokemonLogo";
import VerticalScrollImage from "@/components/VerticalScrollImage";
import PikachuArrive from "@/components/PikachuArrive";
import { ImageContext } from "@/context/ImageProvider";

export default function Home() {
  const { setImage } = useContext(ImageContext);

  // States
  const [data, setData] = useState([]);

  // Styles
  const bgImage = {
    backgroundImage: "url('/Background.png')",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
  };

  // Fetch Data
  const fetchData = () => {
    const gqlQuery = `query pokemons($limit: Int, $offset: Int) {
      pokemons(limit: $limit, offset: $offset) {
        count
        next
        previous
        status
        message
        results {
          id
          url
          name
          image
          artwork
        }
      }
    }`;

    const gqlVariables = {
      limit: 12,
      offset: 1,
    };

    fetch("https://graphql-pokeapi.graphcdn.app/", {
      credentials: "omit",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        query: gqlQuery,
        variables: gqlVariables,
      }),
      method: "POST",
    })
      .then((res) => res.json())
      .then((res) => setData(res.data));
  };

  // Componenent did mount
  useEffect(() => fetchData(), []);

  return (
    <>
      <Head>
        <title>PokeDex - Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://icons-for-free.com/iconfiles/png/512/go+pikachu+play+pokemon+icon-1320186973527720987.png"
        />
      </Head>
      <main>
        {/* Pokemon Cards Container */}
        <div style={bgImage}>
          <SectionContainer>
            <PokemonLogo />
            {/* Card Container */}
            <div className=" py-16">
              {/* Larger Screen */}
              <div className="hidden md:flex overflow-hidden justify-center md:flex-wrap flex-nowrap gap-2 md:gap-10 justify-self-center  ">
                {data?.pokemons?.results.map((pokemon) => (
                  <Link
                    href={{
                      pathname: "/pokemon/[name]",
                      query: { name: pokemon.name },
                    }}
                    onClick={() => setImage(pokemon.artwork)}
                  >
                    <PokemonCard key={pokemon.id} pokemon={pokemon} />
                  </Link>
                ))}
              </div>
              {/* Small Screen */}
              <div className="block md:hidden">
                <Swiper
                  slidesPerView={2}
                  spaceBetween={30}
                  centeredSlides={true}
                  navigation={true}
                  modules={[Navigation]}
                  className="mySwiper"
                >
                  {data?.pokemons?.results.map((pokemon) => (
                    <SwiperSlide>
                      <Link
                        href={{
                          pathname: "/pokemon/[name]",
                          query: {
                            name: pokemon.name,
                          },
                        }}
                        onClick={() => setImage(pokemon.artwork)}
                      >
                        <PokemonCard key={pokemon.id} pokemon={pokemon} />
                      </Link>
                    </SwiperSlide>
                  ))}
                </Swiper>
              </div>
            </div>
          </SectionContainer>
        </div>

        {/* Poke News Container */}
        <div className=" grid md:grid-cols-[80px_1fr_80px]">
          {/* Left scrolling Image */}
          <VerticalScrollImage />
          {/* Main Content */}
          <SectionContainer>
            <div className="relative">
              <img
                src="/Brush.png"
                className="absolute w-1/2 md:max-w-fit top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 -z-10"
                alt=""
              />
              <h2 className="text-3xl lg:text-5xl font-extrabold py-10 md:py-20 text-[#0081c9] text-center">
                Ash & Pikachu Arrive in <br /> Pokemon Universe
              </h2>
            </div>
            <PikachuArrive />
          </SectionContainer>
          {/* Right Scrolling Image */}
          <VerticalScrollImage />
        </div>
      </main>
    </>
  );
}
